config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'
  get 'render/index'
  # Create User Page
  get '/sign-up', to: 'users#new', as: 'sign-up'

  # Login Routes
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  # Users routes
  namespace :api do
    namespace :v1 do
      resources :posts
    end
  end

  resources :friendships, only: [:create, :destroy, :update]

  get '/search', to: 'users#search', as: 'search_users'

  resources :users, only: [:create, :show, :index, :destroy] do
    member do
      patch 'update_password'
      patch 'update_username'
      patch 'update_bio'
      patch 'update_profile_picture'
    end
  end

  resources :posts do
    resources :comments, only: [:create]
  end

  post 'posts/:id/like', to: 'likes#like_post', as: 'like_post'
  delete 'posts/:id/unlike', to: 'likes#unlike_post', as: 'unlike_post'

  post 'comments/:id/like', to: 'likes#like_comment', as: 'like_comment'
  delete 'comments/:id/unlike', to: 'likes#unlike_comment', as: 'unlike_comment'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/models/user.rb
class User < ApplicationRecord

  # Fields
  validates :username, presence: true, length: { maximum: 20 }, uniqueness: true
  validates :password, presence: true, on: :create
  validates :bio, length: { maximum: 150 }
  has_secure_password

  #Associations
  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, dependent: :destroy

  has_many :friendships
  has_many :friends, -> { where(friendships: { status: :accepted }) }, through: :friendships, source: :friend
  has_many :friend_requests, -> { where(requester_id: :user1, status: :pending) }, class_name: 'Friendship', foreign_key: 'user_id'
  # Profile Picture Handling

  DEFAULT_PROFILE_PICTURE = "default_pfp.png"
  MAX_IMAGE_SIZE = 2.megabytes
  MAX_IMAGE_DIMENSION = 300

  has_one_attached :profile_picture
  before_create :set_default_profile_picture

  def friends_posts
    friend_ids = friends.pluck(:id)
    Post.where(author: friend_ids)
  end

  def accepted_friendships
    Friendship.where(user_id: id, status: :accepted)
  end

  def self.search(query)
    where("username LIKE ?", "%#{query}%")
  end

  private
  def set_default_profile_picture
    self.profile_picture.attach(io: File.open("#{Rails.root}/app/assets/images/#{DEFAULT_PROFILE_PICTURE}"), filename: DEFAULT_PROFILE_PICTURE, content_type: 'image/png') unless profile_picture.attached?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :destroy, :update_password, :update_username, :update_bio, :update_profile_picture]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: 'User was successfully created.'
    else
      flash.now[:alert] = 'Failed to create user. Ensure all fields are filled and passwords match.'
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(created_at: :desc).page(params[:page])
    @friends = @user.friends
  end

  def index
    @users = User.all
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  def search
    @query = params[:query]
    @users = User.where('username LIKE ?', "%#{@query}%")
  end

  def update_password
    if @user&.authenticate(params[:current_password])
      if @user.update(password: params[:new_password])
        redirect_to @user, notice: 'Password was successfully updated.'
      else
        flash.now[:alert] = 'Error updating password.'
        render :show, status: :unprocessable_entity
      end
    else
      flash.now[:alert] = 'Error updating password.'
      render :show, status: :unprocessable_entity
    end
  end

  def update_username
    if @user.update(username: params[:new_username])
      redirect_to @user, notice: 'Username was successfully updated.'
    else
      flash.now[:alert] = 'Error updating username.'
      @posts = @user.posts.order(created_at: :desc).page(params[:page])
      render :show
    end
  end

  def update_bio
    if @user.update(bio_params)
      redirect_to @user, notice: 'Bio was successfully updated.'
    else
      flash.now[:alert] = 'There was an error updating your bio.'
      print("error")
      @posts = @user.posts.order(created_at: :desc).page(params[:page])
      render :show
    end
  end

  def update_profile_picture
    if @user.update(profile_picture: params[:user][:profile_picture])
      redirect_to @user, notice: 'Profile picture was successfully updated.'
    else
      flash.now[:alert] = 'There was an error updating your profile picture.'
      render :show
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation, :bio, :profile_picture)
  end

  def bio_params
    params.require(:user).permit(:bio)
  end
end

app/views/users/new.html.erb
<div class="row text-center justify-content-center">
  <div class="col dflex align-items-center">
    <h1>Sign-Up</h1>
    <% if flash[:alert] %>
      <div class="alert alert-danger" role="alert">
        <%= flash[:alert] %>
      </div>
    <% end %>
    <%= form_with model: @user do |form| %>
      <div class="mb-3">
        <%= form.label :username %>
        <%= form.text_field :username, class: "form-control", placeholder: "Your display name" %>
      </div>
      <div class="mb-3">
        <%= form.label :password %>
        <%= form.password_field :password, class: "form-control", placeholder: "Password" %>
      </div>
      <div class="mb-3">
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation, class: "form-control", placeholder: "Confirm your password" %>
      </div>
      <div class="mb-3">
        <%= form.submit "Register", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/search.html.erb
<%= form_with(url: search_users_path, method: :get) do |form| %>
  <%= form.text_field :query, placeholder: "Search users..." %>
  <%= form.submit "Search" %>
<% end %>

<% if @users.any? %>
  <% @users.each do |user| %>
    <div class="listing">
        <%= link_to user_path(user), style: "text-decoration: none;" do %>
            <% if user.profile_picture.attached? %>
                <%= image_tag user.profile_picture, class: "profile-picture", style: "width: 150px; height: 150px;"%>
            <% else %>
                <img src="default_pfp.png" alt="Default Profile Picture" class="profile-picture" width="150" height="150">
            <% end %>
        <% end %>
        <%= link_to user_path(user) do %>
            <%= user.username %>
        <% end %>
    </div>
  <% end %>
<% else %>
  <p>No users found</p>
<% end %>

app/views/users/show.html.erb
<div class="container">
  <div class="user-profile">
    <% if current_user != @user %>
        <% if current_user.friends.include?(@user) %>
            <%= button_to "Remove Friend", friendship_path(current_user.friends.find_by(id: @user.id)), method: :delete %>
        <% elsif current_user.friend_requests.exists?(friend: @user) %>
            <%= button_to "Cancel Request", friendship_path(@user.id), method: :delete %>
        <% elsif current_user.friendships.exists?(friend: @user) %>
            <%= button_to "Accept Request", friendship_path(@user.id), method: :patch %>
            <%= button_to "Reject Request", friendship_path(@user.id), method: :delete %>
        <% else %>
            <%= button_to "Send Request", friendships_path(friendship: { friend_id: @user.id }), method: :post %>
        <% end %>
    <% end %>
    
    <% if @user.profile_picture.attached? %>
      <%= image_tag @user.profile_picture, class: "profile-picture", style: "width: 300px; height: 300px;" %>
    <% else %>
      <%= image_tag "default_pfp.png", class: "profile-picture", style: "width: 300px; height: 300px;" %>
    <% end %>
    <h1><%= @user.username %></h1>
    <p>Bio: <%= @user.bio %></p>

    <% if @user == current_user %>
      <%= form_with(model: @user, url: update_bio_user_path(@user), method: :patch, local: true, html: { id: "update_bio_form" }) do |form| %>
        <% if @user.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@user.errors.count, "error") %> prohibited this bio from being saved:</h2>
            <ul>
              <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-group">
          <%= form.label :bio, "Update Bio" %>
          <%= form.text_area :bio, class: "form-control", id: "bio_text_area" %>
        </div>
        <div class="form-group">
          <%= form.submit "Update Bio", class: "btn btn-primary", id: "update_bio_button" %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="friends-list">
    <h2>Friends</h2>
    <% if @user.friends.any? %>
        <ul>
            <% @user.friends.each do |friendship| %>
            <li><%= link_to friendship.username, friendship %></li>
            <% end %>
        </ul>
    <% else %>
      <p>No friends yet.</p>
    <% end %>
  </div>

  <div id="posts">
    <% if @user == current_user%>        
      <%= render partial: "shared/new_post", locals: { post: Post.new } %>
    <% end %>
    <% if @posts.any? %>
      <%= render @posts %>
    <% else %>
      <p>No posts found.</p>
    <% end %>
  </div>

  <%= paginate @posts, window: 2 %>
</div>