config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'
  get 'render/index'
  # Create User Page
  get '/sign-up', to: 'users#new', as: 'sign-up'

  # Login Routes
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  # Users routes
  namespace :api do
    namespace :v1 do
      resources :posts
    end
  end

  resources :friendships, only: [:create, :destroy, :update]

  get '/search', to: 'users#search', as: 'search_users'

  resources :users, only: [:create, :show, :index, :destroy] do
    member do
      patch 'update_password'
      patch 'update_username'
      patch 'update_bio'
      patch 'update_profile_picture'
    end
  end

  resources :posts do
    resources :comments, only: [:create]
  end

  post 'posts/:id/like', to: 'likes#like_post', as: 'like_post'
  delete 'posts/:id/unlike', to: 'likes#unlike_post', as: 'unlike_post'

  post 'comments/:id/like', to: 'likes#like_comment', as: 'like_comment'
  delete 'comments/:id/unlike', to: 'likes#unlike_comment', as: 'unlike_comment'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= current_user ? user_path(current_user) : '#' %>">Profile</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
      </ul>
      <%= form_tag(search_users_path, method: :get, class: "d-flex me-auto") do %>
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
        <button class="btn btn-outline-success" type="submit">Search</button>
      <% end %>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if session[:user_id] %>
          <li class="nav-item">
            <%= button_to "Logout", logout_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", login_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", sign_up_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_new_post.html.erb
<div class="post-input">
  <%= form_with model: post, url: posts_path, remote: true, id: "new_post_form" do |form| %>
    <%= form.text_area :content, class: "form-control mb-3", placeholder: "What's on your mind?" %>
    <%= form.submit "Post", class: "btn btn-primary" %>
  <% end %>
</div>