config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'
  get 'render/index'
  # Create User Page
  get '/sign-up', to: 'users#new', as: 'sign-up'

  # Login Routes
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  # Users routes
  namespace :api do
    namespace :v1 do
      resources :posts
    end
  end

  resources :friendships, only: [:create, :destroy, :update]

  get '/search', to: 'users#search', as: 'search_users'

  resources :users, only: [:create, :show, :index, :destroy] do
    member do
      patch 'update_password'
      patch 'update_username'
      patch 'update_bio'
      patch 'update_profile_picture'
    end
  end

  resources :posts do
    resources :comments, only: [:create]
  end

  post 'posts/:id/like', to: 'likes#like_post', as: 'like_post'
  delete 'posts/:id/unlike', to: 'likes#unlike_post', as: 'unlike_post'

  post 'comments/:id/like', to: 'likes#like_comment', as: 'like_comment'
  delete 'comments/:id/unlike', to: 'likes#unlike_comment', as: 'unlike_comment'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy

  validates :content, presence: true
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  before_action :set_post, only: [:show, :update, :destroy]

  def index
    @posts = Post.all
    render json: @posts
  end

  def show
    render json: @post
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      render json: @post, status: :created
    else
      render json: @post.errors, status: :unprocessable_entity
    end
  end

  def update
    if @post.update(post_params)
      render json: @post
    else
      render json: @post.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy
    head :no_content
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:content, :author_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    @post = Post.new(post_params)
    @post.author = current_user

    respond_to do |format|
      if @post.save
        format.turbo_stream { render turbo_stream: turbo_stream.append("posts", @post) }
        format.html { redirect_to root_path, notice: "Post was successfully created." }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace("new_post_form", partial: "shared/new_post", locals: { post: @post }) }
        format.html { render :new }
      end
    end
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<div class="post">
  <p><small><%= post.author.username %> <%= post.created_at.strftime("%B %d, %Y %I:%M %p") %></small></p>
  <p><%= post.content %></p>

  <div id="post_<%= post.id %>_likes">
    <p>Likes: <%= post.likes.count %></p>
    <% if post.likes.exists?(user: current_user) %>
      <%= button_to 'Unlike', unlike_post_path(post), method: :delete, remote: true %>
    <% else %>
      <%= button_to 'Like', like_post_path(post), method: :post, remote: true %>
    <% end %>
  </div>

  <ul>
    <% post.comments.each do |comment| %>
      <li>
        <%= comment.content %>
        <div id="comment_<%= comment.id %>_likes">
          <span>Likes: <%= comment.likes.count %></span>
          <% if comment.likes.exists?(user: current_user) %>
            <%= button_to 'Unlike', unlike_comment_path(comment), method: :delete, remote: true %>
          <% else %>
            <%= button_to 'Like', like_comment_path(comment), method: :post, remote: true %>
          <% end %>
        </div>
        <p><small><%= comment.author.username %> <%= comment.created_at.strftime("%B %d, %Y %I:%M %p") %></small></p>
      </li>
    <% end %>
  </ul>

  <%= form_with(model: [post, Comment.new], local: true) do |form| %>
    <%= form.text_area :content, placeholder: 'Add a comment...' %>
    <%= form.submit 'Comment' %>
  <% end %>
</div>

app/views/posts/create.js.erb
$('#posts').prepend('<%= j render(@post) %>');
$('#new_post_form')[0].reset();